version: '2'

services:
  db:
    image: postgres
    networks:
      - diga_network

  web:
    restart: always
    build: .
    command: python apps/manage.py runserver 0.0.0.0:8000
    environment:
      - VIRTUAL_HOST=robosapiens.icu
      - VIRTUAL_PORT=8066
      - LETSENCRYPT_HOST=robosapiens.icu
      - LETSENCRYPT_EMAIL=admin@robosapiens.icu
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - diga_network
    depends_on:
      - db

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - diga_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "certs:/etc/nginx/certs:ro"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/etc/nginx/certs:rw"
    networks:
      - diga_network

volumes:
  certs:

networks:
  diga_network:
    external: true